### ISSUE TITLE
Conflict with Seti UI theme

### ISSUE THREAD

**Issue by benadamstyles** [blomma/one-tab#1]
Getting the following behaviour:

<img width="692" alt="screen shot 2015-08-07 at 11 50 06" src="https://cloud.githubusercontent.com/assets/4380655/9134289/994a7178-3cfa-11e5-8b2a-3398cc7fe539.png">

I assume this is due to a conflict with my UI theme which is [Seti](https://atom.io/themes/seti-ui). Any chance you could take a look at this?

**Comment by blomma** [comment]
Ohhh that looks exciting and so very wrong, ill take a look at it.

**Comment by benadamstyles** [comment]
Thanks. If you need anything from me just ask.

**Comment by benadamstyles** [comment]
Can confirm this works, thanks!
