### ISSUE TITLE
One tab not hidden

### ISSUE THREAD

**Issue by orschiro** [blomma/one-tab#2]
Dear @blomma,

Thank you very much for this package. I would love to hide the tab bar if only one tab is used. However, I fail to use the package properly. 

I installed it but the tab bar is not hiding when only using one tab. 

Could you please have a look at the below screencast?

Thankfully, 

Robert

[one-tab-2015-10-04_12.35.07.mkv | uploaded via ZenHub](https://files.zenhub.io/5611011e024bad464a827ace)

**Comment by blomma** [comment]
Sorry for the long delay, could you show me what settings you have on the built in tabs package, and also could you give me a list of which packages you are using, I'm having a hard time reproducing the problem and there might be some conflict between packages here.

**Comment by orschiro** [comment]
Dear @blomma,

In the meantime the problem was resolved. I think it was some incompatibility with other packages. 

Now, the tab bar is correctly being hidden. 

Thank you!

~ Robert
